config/routes.rb
Models::Application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'users#dashboard'
  end
  devise_for :users , path_names: { sign_in: "login", sign_out: "logout"} ,controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  
 scope :module => 'site', :constraints => { :subdomain => /.+/ } do
    root :to =>'sites#show'
    get 'about', to: 'users#show'
    get 'books', to: 'books#index'
    get 'book/:id', to: 'books#show', as: "pictures"
    get "contact", to: 'contact#show'
  end

  resources :users, only: [ :show ]


  namespace :akira do
    resources :photographers
    resources :models
    
    resources :users do
      collection do
        get 'dashboard'
      end
      put 'check'
      resources :books
      resources :sites
      resources :jobs
    end
  end

  namespace :home do
    resources :jobs, only: [:index, :show ]
    resources :sites
    resources :users, only: [:index, :show ]
    
  end

  root :to => "home#index"
  


end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes

  #after_validation :subdomain_valid

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
    :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String , :default =>""
  field :encrypted_password, :type => String

  ##Personaldata

  field :name ,:type => String
  field :firstname, :type => String
  field :lastname, :type => String
  field :nationality, :type => String
  field :ubication , :type => String
  field :subdomain , :type => String
  field :description, :type => String
  field :zip_code, :type => Integer
  field :address, :type => String
  field :tel, :type => Integer
  field :cel, :type => Integer
  field :_type, :type => String
  field :active, :type => Boolean, :default => false

  ##Social data
  field :tw, :type => String
  field :provider, :type => String
  field :facebook, :type => String
  field :twitter, :type => String
  field :google, :type => String
  field :instagram, :type => String

  ## flag for profile
  field :check, :type => Boolean, :default => false
  ## Site Data
  field :specialty, :type => String
  field :general_description , :type => String
  field :professional_description , :type => String 

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time
  field :address, :type => String
  field :tel, :type => Integer
  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String
  field :_type, :type => String, :default => "Model"

  ##picture

  field :photo, :type => String
  ##relations

  has_many :books
  has_and_belongs_to_many :tags
  has_one :site
  embeds_many :networks
  has_and_belongs_to_many :jobs



  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
  # run 'rake db:mongoid:create_indexes' to create indexes
  index({ email: 1 }, { unique: true, background: true })


  ## aceppts attributes
  accepts_nested_attributes_for :books 
  accepts_nested_attributes_for :site

  ##validate
  validates_presence_of :name 
  validates_presence_of :email
  validates_presence_of :encrypted_password
  validates_presence_of :_type

  mount_uploader :photo, ImageUploader
  #validate subdomain



  #attributes accessibles

  attr_accessible :tag_ids, :check,:instagram,:google,:twitter,:facebook,:specialty,:firstname,:tw,:provider, :professional_description,:address,:tel,:general_description,:photo, :name, :subdomain ,:email, :password, :password_confirmation, 
    :remember_me,:ubication, :created_at, :updated_at , :_type, :contry ,:state ,:site_attributes,:description

   # validates_presence_of :subdomain
   # validates_uniqueness_of :subdomain
    
    #validates_exclusion_of :subdomain, :in => %w( www ftp api support blog billing help smtp ), :message => "The subdomain <strong>{{value}}</strong> is reserved and unavailable."
   
    #validates_format_of :subdomain, :with => /^[A-Za-z0-9-]+$/ 
   
  def subdomain_valid
    p "ok"
    p self.subdomain
    self.subdomain = self.subdomain.downcase 
    p self.subdomain
  end


  def self.find_for_oauth(auth, signed_in_resource=nil)
    user = User.where(email: auth.info.email).first
    unless user
      user = User.create!(
        name: auth.info.name,
        email: auth.info.email,
        password:Devise.friendly_token[0,20],
        provider:auth.provider
        )
    end

    user
  end

    def self.new_with_session(params, session)
      if session["devise.user_attributes"]
        new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
      user.valid?
      end
      else
        super
      end
    end

end

app/controllers/akira/users_controller.rb
class Akira::UsersController < ApplicationController
  layout 'akira'
  
  def index
    @users = User.all
  end

  def show
    begin
      @user = User.find_by(subdomain: request.subdomain)
    rescue Exception => e
      logger.warn "Unable to foo, will ignore: #{e}"
      redirect_to new_user_registration_path
      render layout: 'site'
    end
  end


  def dashboard
    @user = current_user
  end


  def create
    respond_to do |format|
    	if @user = User.new(params)
        format.html { redirect_to redirect_register_users_path , notice: '#{@user._type} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @user, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  def edit
    
  end


  def check
    @user = User.find(params[:user_id])

    respond_to do |format|
      if @user.update_attributes!(params[:model])
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @model = User.find(params[:id])

    respond_to do |format|
      if @model.update_attributes!(params[:user])
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/home/users_controller.rb
class Home::UsersController < ApplicationController
  def index
    @users = User.where(active: true)
   
  end
  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/site/users_controller.rb
class Site::UsersController < ApplicationController
  layout 'sites'

  def show
  	
     @user = User.find_by(subdomain: request.subdomain)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def dashboard
    @user = current_user
      if @user.site
        @site = @user.site
      else
        @user.site = Site.new
      end
      render layout: "akira"
  end


  def create
    respond_to do |format|
    	if @user = User.new(params)
        format.html { redirect_to redirect_register_users_path , notice: '#{@user._type} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @user, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end
  
end

app/helpers/user_helper.rb
module UserHelper
	def twitter(user)
		begin
			
		rescue Exception => e
		
		end
	end
	def facebook(user)
		begin
			uri = URI.parse("https://graph.facebook.com/#{user}")
			req = Net::HTTP.get_response(uri)
			parsed_json = ActiveSupport::JSON.decode(req)
			p parsed_json
		rescue Exception => e
			p "se#{e}"
		end
		parsed_json
	end
	def instagram(user)
		begin
			
		rescue Exception => e
			
		end
	end
end

app/views/users/_nav.html.erb
<div class="row">
	<div class="large-4 columns">
		<h2 class="subheader"><%=link_to "Nombre modelo", root_path%></h2>
	</div>
<div class="large-8 columns">
	<ul class="inline-list right">
	  <li><%= link_to "Perfil", root_path%></li>
	  <li><a href="#">Estadisticas</a></li>
	  <li><%= link_to "Books", akira_user_books_path(current_user.id)%></li>
	</ul>
</div>


	<hr>
</div>

app/views/users/_profile.html.haml
.col-sm-2.col-md-3.col-lg-3.pading_profile.hidden-xs
	=link_to image_tag(current_user.photo ,:class=>"img-profile") , "#myPicture" , :"data-toggle"=>"modal"
	.list-group
		= link_to "Editar", edit_akira_model_path(current_user), :class=>"list-group-item"

		= link_to "Portafolio oline", edit_akira_user_site_path(current_user, current_user.site), :class=>"list-group-item"
		
		= link_to "Books", akira_user_books_path(current_user), :class=>"list-group-item"
		
		= link_to "Ofetas Laborales", akira_user_jobs_path(current_user), :class=>"list-group-item"
		= link_to "Salir", destroy_user_session_path, :class=>"list-group-item",:method =>:DELETE

.modal.fade#myPicture{:tabindex=>"-1", :role=>"dialog", :"aria-labelledby"=>"myModalLabel", :"aria-hidden"=>"true"}
	.modal-dialog
		.modal-content
			.modal-header
				%h5
					Cambiar su foto de perfil
			.modal-body
				= form_tag akira_user_path(current_user),:multipart => true ,:method => :put  do |f|
					.img-thumbnail
						= image_tag current_user.photo, :class=>"img_upload"
					= fields_for :user do |a|
						.form-group
							= a.file_field :photo, :class=>"form-control"
					.form-group
						.pull-right
							=submit_tag "Cambiar Imagen", :class=>"btn btn-default"


:javascript
	$('#myPicture').on('hidden.bs.modal', function (){
	  // do something…
	});

app/views/users/dashboard.html.haml
.col-xs-12.col-sm-12.col-md-9.col-lg-9
	=render 'akira/partials/nav_profile'
	.row.head_akira

		.col-xs-12.col-sm-12.col-md-12.col-lg-12
			.row
				.col-xs-3.col-sm-3.col-md-3.col-lg-3.center
					.social_icon.img-circle.face
						%span.icon-briefcase
						%p
							Ofetas
					
				.col-xs-3.col-sm-3.col-md-3.col-lg-3.center
					.social_icon.img-circle.twiter
						%span.icon-calendar
						%p
							Eventos

				.col-xs-3.col-sm-3.col-md-3.col-lg-3.center
					.social_icon.img-circle.instagram
						%span.icon-mail
						%p
							Mensajes
				.col-xs-3.col-sm-3.col-md-3.col-lg-3.center
					.social_icon.img-circle.views
						%span.icon-chart
						%p
							Visitas
	.row
		.col-xs-12.col-sm-12.col-md-12.col-lg-12.nav_event
		
	.row
		.col-xs-12.col-sm-12.col-md-12.col-lg-12.stream
			.media
				.pull-left
					= image_tag "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-ash2/c54.0.260.260/s160x160/1381706_613702502021168_1701884661_n.jpg",:class=>"img-circle media-object"
				.media-body
					.media-heading
						%h4
							Bienvenido a IsFamous
							%small.pull-right
								=@user.created_at.to_date.to_formatted_s(:rfc822) 
						%p
							Apartir de este momento podras disfrutar de todos los b b beneficios que te brindamos por pertenecer a nuestra comunidad.
							%br
							Te invitamos a crear tu web y mostarrle al mundo lo importate que eres.
							

app/views/users/index.html.erb
Hola q hace
<div class="container_show">
	<div class="row">
		<div class="small-6 large-4 columns">
			<div class="black">
				<em>“Give a girl the right shoes, and she can conquer the world.”</em>
			</div>
		</div>
		
		<% @users.each do |user| %>
	    <div class="small-6 large-4 columns">
	    	<div class="marco">
	    		<img src="http://placehold.it/288x200">
	    		<h3 class="subheader"><%= user.name %></h3>
	    		<%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
	    	</div>
	    </div>
	  <% end %>

	</div>
</div>