config/routes.rb
Models::Application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'users#dashboard'
  end
  devise_for :users , path_names: { sign_in: "login", sign_out: "logout"} ,controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  
 scope :module => 'site', :constraints => { :subdomain => /.+/ } do
    root :to =>'sites#show'
    get 'about', to: 'users#show'
    get 'books', to: 'books#index'
    get 'book/:id', to: 'books#show', as: "pictures"
    get "contact", to: 'contact#show'
  end

  resources :users, only: [ :show ]


  namespace :akira do
    resources :photographers
    resources :models
    
    resources :users do
      collection do
        get 'dashboard'
      end
      put 'check'
      resources :books
      resources :sites
      resources :jobs
    end
  end

  namespace :home do
    resources :jobs, only: [:index, :show ]
    resources :sites
    resources :users, only: [:index, :show ]
    
  end

  root :to => "home#index"
  


end

app/controllers/home/jobs_cotroller.rb
class Home::JobsController < ApplicationController
	 # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
    @tags = Tag.all
  end
  def show
  	@job = Job.find(params[:id])
  	if current_user
  		@apply = @job.users.find(current_user)
  	else
  		@apply = nil
  	end
  end

   def update
  	user = current_user
  	job = Job.find(params[:id])
  	job.users << user
  	redirect_to home_job_path(job)
  end

end

app/controllers/home/users_controller.rb
class Home::UsersController < ApplicationController
  def index
    @users = User.where(active: true)
   
  end
  def show
  	@user = User.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all.where(active: true).limit(6)
     @jobs = Job.all.limit(4)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
#carousel-home.carousel.slide.carrucel_home
  /Wrapper for slides
  .carousel-inner
    .item.active
      = image_tag "images/home1.png"
  /Controls

  %a{ :class=>"left carousel-control", :href=>"#carousel-example-generic", :"data-slide"=>"prev"}
    %span.icon-prev

  %a{ :class=>"right carousel-control",:href=>"#carousel-example-generic", :"data-slide"=>"next"}
    %span.icon-next


%section.info.container
  .row
    .col-sm-4.col-md-4.col-lg-4
      .subtitle
        %h3
          IsFamous
        %hr.gray
      %p
        Si usted es  actor, modelo, fotografo, o profesional del mundo creativo  en busca de su sueño, o un director de casting en busca del talento perfecto para su próximo proyecto, isfamous es el lugar para estar.
        %br
        %br
        Noticias, casting, entrevistas, actulizaciones y mucho mas en un solo lugar. 

    .col-sm-8.col-md-8.col-lg-8
      .row
        .subtitle
          %h3
            Portafolios Destacados
          %hr.gray
        -@users.each do |user|
          .col-sm-6.col-md-6.col-lg-6.famous_list
            .media
              %a.pull-left
                %picture
                  =image_tag user.photo
              .media-body
                %h4.media-heading
                  =user.name
                %p.text-muted
                  %small
                    %em
                      ="(#{user.specialty})"
                    %br
                    = user.ubication
                = link_to "Ver Perfil", home_user_path(user), :class=>"ver"
%section.info.container
  .row
    .subtitle
      %h3
        Audiciones & Trabajos destacados
      %hr.gray
    - @jobs.each do |job|
      .col-xs-12.col-sm-6.col-md-6.col-lg-6.famous_list
        .media
          %a.pull-left
            %picture
              = image_tag job.picture_url(:thumb) , :class => "img_"
          .media-body
            %h4.media-heading
              = link_to job.name, home_job_path(job)
            %p.text-muted
              %small
                %span.icon-direction
                %em
                  ="#{job.ubication}"
              |
              %small
                %span.icon-calendar
                %em
                  ="#{job.date_end}"
            %p
              = truncate(job.description, :length => 100)
              = link_to "Aplicar", home_job_path(job)