config/routes.rb
Models::Application.routes.draw do
  

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :user do
    root :to => 'users#dashboard'
  end
  devise_for :users , path_names: { sign_in: "login", sign_out: "logout"} ,controllers: {omniauth_callbacks: "omniauth_callbacks"}
  ActiveAdmin.routes(self)
  
 scope :module => 'site', :constraints => { :subdomain => /.+/ } do
    root :to =>'sites#show'
    get 'about', to: 'users#show'
    get 'books', to: 'books#index'
    get 'book/:id', to: 'books#show', as: "pictures"
    get "contact", to: 'contact#show'
  end

  resources :users, only: [ :show ]


  namespace :akira do
    resources :photographers
    resources :models
    
    resources :users do
      collection do
        get 'dashboard'
      end
      put 'check'
      resources :books
      resources :sites
      resources :jobs
    end
  end

  namespace :home do
    resources :jobs, only: [:index, :show ]
    resources :sites
    resources :users, only: [:index, :show ]
    
  end

  root :to => "home#index"
  


end

app/models/site.rb
class Site
  include Mongoid::Document
  attr_writer :current_step

  field :visit, type: Integer
  field :title, type: String
  field :keywords, type: String
  field	:description, type: String
  field :subdomain, type: String
  field	:logo, type: String
  field	:slogan, type: String
  field :bg, type: String
  field :contact, type: String 
  
  belongs_to :user
  mount_uploader :bg, BgUploader
  attr_accessible :contact, :bg, :visit, :title, :description, :subdomain, :logo, :slogan


end

app/controllers/akira/books_controller.rb
class Akira::BooksController < ApplicationController
  layout 'akira'
  # GET /books
  # GET /books.json
  def index
    @books = current_user.books

    @book = Book.new
      12.times{@book.pictures.build}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new
    12.times{@book.pictures.build}

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    user = current_user
    @book = Book.new(params[:book])

    respond_to do |format|
      if user.books << @book
        format.html { redirect_to akira_user_books_path(user , @book), notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html {redirect_to akira_user_book_path(user ,@book), notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/akira/jobs_controller.rb
class Akira::JobsController < ApplicationController
	  # GET /jobs/new
  # GET /jobs/new.json
  layout 'akira'
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  def index
    @jobs = current_user.jobs
  end
  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])
    @user = current_user
    respond_to do |format|
      if @user.jobs << @job
        format.html { redirect_to akira_user_job_path(current_user , @job), notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end
  def update
    @job = Job.find(params[:id])
    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to akira_user_job_path(current_user , @job), notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
    @job = Job.find(params[:id])
  end
end

app/controllers/akira/models_controller.rb
class Akira::ModelsController < ApplicationController
  layout "akira"
  # GET /models
  # GET /models.json
  def index
    @models = Model.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @models }
    end
  end

  # GET /models/1
  # GET /models/1.json
  def show
    @model = Model.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @model }
    end
  end


  # GET /models/1/edit
  def edit
    @model = User.find(params[:id])
  end


  # PUT /models/1
  # PUT /models/1.json
  def update
    
    @model = User.find(params[:id])
    p params
    respond_to do |format|
      if @model.update_attributes(params[:model])
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model = Model.find(params[:id])
    @model.destroy

    respond_to do |format|
      format.html { redirect_to models_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/akira/sites_controller.rb
class Akira::SitesController < ApplicationController
  layout 'site_create'
	def new
    @site = Site.new
  end
  # GET /sites/1/edit
  def edit
    @user = current_user
  end

  def update

    @user = User.find(params[:user_id])

    respond_to do |format|
      if @user.update_attributes!(params[:user])
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/akira/users_controller.rb
class Akira::UsersController < ApplicationController
  layout 'akira'
  
  def index
    @users = User.all
  end

  def show
    begin
      @user = User.find_by(subdomain: request.subdomain)
    rescue Exception => e
      logger.warn "Unable to foo, will ignore: #{e}"
      redirect_to new_user_registration_path
      render layout: 'site'
    end
  end


  def dashboard
    @user = current_user
  end


  def create
    respond_to do |format|
    	if @user = User.new(params)
        format.html { redirect_to redirect_register_users_path , notice: '#{@user._type} was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @user, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      end
    end
  end

  def edit
    
  end


  def check
    @user = User.find(params[:user_id])

    respond_to do |format|
      if @user.update_attributes!(params[:model])
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @model = User.find(params[:id])

    respond_to do |format|
      if @model.update_attributes!(params[:user])
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to root_path, notice: 'Model was successfully updated.' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/site/books_controller.rb
class Site::BooksController < ApplicationController
	layout 'sites'
	def show
		@user = User.find_by(subdomain: request.subdomain)
		@book = Book.find(params[:id])
		@pictures = @book.pictures
	end
	def index
		@user = User.find_by(subdomain: request.subdomain)
		@books = @user.books
	end
end

app/controllers/site/contact_controller.rb
class Site::ContactController < ApplicationController
	layout 'sites'
  def show
  	@user = User.find_by(subdomain: request.subdomain)
  end
end

app/controllers/site/sites_controller.rb
class Site::SitesController < ApplicationController
	layout 'sites'
  def show
    begin
      @user = User.find_by(subdomain: request.subdomain)
      @books = @user.books.limit(3)
    rescue Exception => e
      logger.warn "Unable to foo, will ignore: #{e}"
      redirect_to new_user_registration_path
    end
  end


end

app/controllers/site/users_controller.rb
class Site::UsersController < ApplicationController
  layout 'sites'

  def show
  	
     @user = User.find_by(subdomain: request.subdomain)
  end

end

app/helpers/sites_helper.rb
module SitesHelper
	def class_body(type)
		case type
		when "home/users"
			"user_bg"
		when "home/jobs"
			"user_bg"
		end
	end

	def bg_site(url)
		"url(#{url})"
	end


end

app/views/akira/sites/_agent.html.haml
.row.center
	%h3
		Categorias

.row
	-for tag in Tag.all
		.col-xs-12.col-sm-12.col-md-6.col-lg-6
			.form-group
				.checkbox
					= label_tag tag.name
					= check_box_tag "model[tag_ids][]" , tag.id, @user.tags.include?(tag)

	=f.submit "Actualizar" ,class: "btn btn-success btn-lg btn-block"

app/views/akira/sites/_book_step.html.haml
.row.center
	%h3
		Categorias

.row
	-for tag in Tag.all
		.col-xs-12.col-sm-12.col-md-6.col-lg-6
			.form-group
				.checkbox
					= label_tag tag.name
					= check_box_tag "model[tag_ids][]" , tag.id, @user.tags.include?(tag)

	=f.submit "Actualizar" ,class: "btn btn-success btn-lg btn-block"

app/views/akira/sites/_form.html.haml
Agente

app/views/akira/sites/_general_step.html.haml
= f.fields_for :site do |site|
	.row.center
		%h3
			Informacion General

	.row
		.col-xs-12.col-sm-12.col-md-12.col-lg-12
			.form-group
				=site.label :tile, "Titulo"
				=site.text_field :title , class: "form-control", pleaceholder: "Titulo"		

			.form-group
				= f.label :subdomain , "Nombre de su web"
				.input-group

					=	f.text_field :subdomain , :pleceholder =>"Username", :class=>"form-control"
					%span.input-group-addon
						=".isfamous.co"
			.form-group
				= site.label :logo
				= site.file_field :logo, class: "form-control", :pleceholder =>"Ubicacion Actual"	
			.form-group
				=site.label :bg , "Seleciona La imagen de fondo de ti sitio web"
				= site.file_field :bg,  class: "form-control"
		
	.row
		.col-xs-12.col-sm-12.col-md-12.col-lg-12
			.form-group
				= site.label :description , "Description"
				=	site.text_area :description , :pleceholder =>"Sobre ti", :class=>"form-control", :rows => 4
		
			%submit.btn.btn-warning.btn-lg.btn-block.step_nav{:'data-nav'=>"next"}
				Siguiente

app/views/akira/sites/_model.html.haml
.row.center
	%h3
		Descripción

.row
	.col-xs-12.col-sm-12.col-md-12.col-lg-12
		.form-group
			=f.label :professional_description, "Descripcion Profesional"
			=f.text_area :professional_description, :class => "redactor", :rows => 60, :cols => 120
.row
	.col-xs-12.col-sm-12.col-md-6.col-lg-6
		.form-group
			= f.label :genre, "Genero"
			= f.select :genre ,options_for_select([["Femenino", "female"],["Masculino", "male"]],@user.genre),{},:class=>"form-control"
		.form-group
			=f.label :height, "Altura"
			.input-group
				=f.number_field :age, class: "form-control",pleaceholder: "Altura"
				%span.input-group-addon
					Mts
		.form-group
			= f.label :chest, "Pecho"
			.input-group
				= f.text_field :chest, class: "form-control"
				%span.input-group-addon
					Cm
		.form-group
			= f.label :hip, "Cadera"
			.input-group
				=f.number_field :hip, class: "form-control"
				%span.input-group-addon
					Cm

		.form-group
			= f.label :hair_color, "Color de cabello"
			= f.select :hair_color ,options_for_select([["Castaño", "Castaño"],["Negro", "Negro"],["Rojo", "Rojo"],["Rubio", "Rubio"],["Blanco", "Blanco"]],@user.hair_color),{},:class=>"form-control"

	.col-xs-12.col-sm-12.col-md-6.col-lg-6

		.form-group
			= f.label :waist, "Cintura"
			.input-group
				=f.number_field :waist, class: "form-control"
				%span.input-group-addon
					Cm
		.form-group
			= f.label :weight, "Peso"
			.input-group
				=f.number_field :weight, class: "form-control"
				%span.input-group-addon
					Kg
		.form-group
			= f.label :eye_color, "Color de ojos"
			= f.select :eye_color ,options_for_select([["Azules", "Azules"],["Negros", "Negros"],["Marrones", "Marrones"],["Verdes", "Verdes"],["Miel", "Miel"]],@user.eye_color),{},:class=>"form-control"

		.form-group
			= f.label :skin, "Color de piel"
			= f.select :skin ,options_for_select([["Negro", "Negro"],["Mulato", "Mulato"],["Blanco", "Blanco"]],@user.skin),{},:class=>"form-control"
		.form-group
			= f.label :hair_length, "Longitud"
			= f.select :hair_length ,options_for_select([["Corto", "Corto"],["Largo", "Largo"],["Medio", "Medio"],["Sin Pelo", "Sin Pelo"]],@user.hair_length),{},:class=>"form-control"

.row
	.col-xs-12.col-sm-12.col-md-12.col-lg-12
		%submit.btn.btn-warning.btn-lg.btn-block.step_nav{:'data-nav'=>"next"}
			Siguiente

app/views/akira/sites/_professional.html.haml
.row.center
	%h3
		Descripción

.row
	.col-xs-12.col-sm-12.col-md-12.col-lg-12
		.form-group
			=f.label :general_description, "Descripción Corta"
			=f.text_area :general_description,  :class => "form-control", :rows => 5
	.col-xs-12.col-sm-12.col-md-12.col-lg-12
		.form-group
			=f.label :professional_description, "Descripción general y Profesional"
			=f.text_area :professional_description,:class => "redactor", :rows => 60, :cols => 120

.row
	.col-xs-12.col-sm-12.col-md-12.col-lg-12
		%submit.btn.btn-warning.btn-lg.btn-block.step_nav{:'data-nav'=>"next"}
			Siguiente

app/views/akira/sites/edit.html.haml
.row
	.col-xs-12.col-sm-12.col-md-4.col-lg-4.stream
		
		= form_for(@user, :url=> akira_user_site_path(@user),:as => :user) do |f|
			
			.page
				=render "akira/sites/general_step", f: f
			.page.hidden
				=render "akira/sites/#{current_user._type.downcase}", f: f
			.page.hidden
				=render "akira/sites/book_step", f: f
			
			
			

		.col-xs-12.col-sm-12.col-md-7.col-lg-7

app/views/akira/sites/index.html.erb
<h1>Listing sites</h1>

<table>
  <tr>
    <th>Visit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sites.each do |site| %>
  <tr>
    <td><%= site.visit %></td>
    <td><%= link_to 'Show', site %></td>
    <td><%= link_to 'Edit', edit_site_path(site) %></td>
    <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site', new_site_path %>

app/views/akira/sites/new.html.haml
%h2
	Configuracion General

=render "form"

app/views/akira/sites/show.html.erb
<p id="notice"><%= notice %></p>

<div class="large-8 columns back ">
  <div class="content">
  	hola
  	<p>

    <p>
    	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>
    	 	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>
    	 	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </p>
  </div>
</div>